### ISSUE TITLE
Require nfPktDecode undefined

### ISSUE THREAD

**Issue by fraxken** [delian/node-netflowv9#15]
Hi,

When i try to require nfPktDecode like in your readme.md that does'nt work. (The decoder is equal to undefined). And all of decoder prototype seems to be not linked to the Collector Object.

```js
const netflowPktDecoder = require('node-netflowv9').nfPktDecode;
console.log(netflowPktDecoder) // undefined
```

Same result with : nf9PktDecode 

Can you look why ? I'm working on NodeJS V6. 

Best Regards,
Thomas

**Comment by delian** [comment]
This is not how it is supposed to be used.
The collector should be accessed with

const Collector = require('node-netflowv9');

It would be hard to access a particular function the way they are exported
(may be I have to put some thoughts on it).
However, you could still do it by doing:

const netflowPktDecoder = require('node-netflowv9').prototype.nfPktDecode;



Delian

**Comment by fraxken** [comment]
No he say to me : this.nf9PktDecode is not a function when i use : 

const netflowPktDecoder = require('node-netflowv9').prototype.nfPktDecode;

**Comment by fraxken** [comment]
And with nf9PktDecode he say to me this.nfInfoTemplates is not a function (i use Netflow V9)

**Comment by delian** [comment]
Yes, looks like the new method leaves the whole space private. Let me think
of how to export it properly

**Comment by fraxken** [comment]
Hi,

Maybe if you bind directly your sub-class to this context in the Netflow constructor like 

this.nf9PktDecode = nf9PktDecode; 

And you move the nfPktDecode function into the class too. I'm not at home right now, but if you want i can made a pull-request to fix that later.

Best Regards,
Thomas

**Comment by fraxken** [comment]
Ok i success to fix on my side (but i see a lot of problem). So i have to dev and test a full fixed version on my side.

**Comment by fraxken** [comment]
I see no documentation to make a template. I dont understand your little example for template argument. 235 is the sourceId or the buffer.byteLength or ??? 

Do you have a real example ?

**Comment by fraxken** [comment]
Ok i see how it's work now :) (First time :D)

**Comment by delian** [comment]
Sorry, I was a little sick those days, and I was not following the github
mails.
Tell me what you mean by template?
Decoding a new option type? Or Cisco Option Template?


Delian

**Comment by delian** [comment]
What do you mean? How did you fix it?
"Ok i success to fix on my side (but i see a lot of problem). So i have to
dev and test a full fixed version on my side.
"


Delian

**Comment by delian** [comment]
Give me example of what you wish to achieve and how it is affected by the
current scope issue?
Generally, each of the submodules are supposed to share the scope of the
NetFlowV9 class. The reason is, to be able to access this.template, which
is not global in order to allow the module to be instantiated multiple
times without poisoning the template cache.

It is interesting why the prototypes are not visible outside the module, I
have to check what is the behavior of the new Node versions there.
In any case, even to access them directly you shall first instantiate the
class (or you will not have a template which is the issue you are having).

The rest of the methods of accessing the module are still working, so you
could try some of them.

Generating a decoder for a new option with NF9 is relatively easy (as long
as you know how to decode it, you shall never receive undefined, you shall
receive it in HEX format).

However, it is possible that the scoping rules has been changed in the
newer versions of the Node, so I am going to try to find potential issues
and to fix it, but it will be great if you can provide me with example
where it breaks?


Delian

**Comment by fraxken** [comment]
For my NodeJS code i have something like that : 

```js
const Collector = require('node-netflowv9');
const Decoder = Collector.prototype.nf9PktDecode;

Decoder.templates = {}; 

Collector({port: 9995})
.on('data',function(flow) {
    console.log("Flow incomming");
    console.log(Decoder(flow.packet,flow.rinfo);
    // I want my flows information here!
})
.on('template',function(data) {
    console.log("template incomming");
    console.log(data);
    var id = data.rinfo.address + ':' + data.rinfo.port;
    // Add template to the nf9PktDecode templates list!
    if(Decoder.templates[id] === undefined) {
        Decoder.templates[id] = data.templates; 
    }
});
``` 
I dont have my computer with the project and the Wireshark. But with this code i have an empty flow array. 

So i dont know if i have to made a nfTypes or something like that or if the template is wrong (if i have to use a specific function of your class etc..)

**Comment by fraxken** [comment]
Screenshot of my wireshark : http://imgur.com/a/c7aPN

**Comment by fraxken** [comment]
So i try to get data from flowset, but the flow array on my program is empty. Or one time with wrong values (when Buffer fail to decode correctly i suppose).

**Comment by fraxken** [comment]
Ok i think i need to add nfTypes and nfScope ( because they have for value { } ) but i'm not sure.

**Comment by fraxken** [comment]
I have something like that : 

![image](https://cloud.githubusercontent.com/assets/4438263/19448942/16a2d384-94a4-11e6-9f82-caaa6c239978.png)

I think i have to create a new nfTypes to match my profile correctly no ? I work on that but it's hard.

**Comment by fraxken** [comment]
the NetFlow Type ID is the sourceId ? 

If you want to see my full template : 

![](http://i.imgur.com/gua7LzR.png)

**Comment by fraxken** [comment]
It's weird because it's seems you already make the code to translate my flows correctly (if i understand your code).

**Comment by fraxken** [comment]
On your code i see 

```js
templates[tId] = { len: plen, compiled: new Function('buf','nfTypes',cr) };
```

It's weird. Do i have to call one of your function to transform my template correctly ? Your package is not very clear about that.

**Comment by fraxken** [comment]
Okay i read all the code to understood when you use compile,readOptions etc ... (So i see how you made the compiled function) So my last chance is the nfTypes.  After that no idea... -_-'

**Comment by fraxken** [comment]
I made a ES6 update : http://pastebin.com/SG5awZRt

It's a first prototype but i work on it (replace all var). I found a problem with template scope between main class and decoder function.

The best solution for maintenable project is still TypeScript to get clear code with typings and possibility to compile to ES6,ES5,ES3 etc..

**Comment by delian** [comment]
I am traveling at the moment. As soon as I get back I will look at it


Delian

**Comment by fraxken** [comment]
i'm working on a fork (you can find on the fork list). When i have something complete i make a Pull-request (but my package contain a lot of breaking change i think). 

Maybe with better unit-testing to prevent this kind of problem.

**Comment by fraxken** [comment]
If you want to see : https://github.com/fraxken/node-netflowv9 (i fix my bug with my version)
