### ISSUE TITLE
Netflow v9 Issue

### ISSUE THREAD

**Issue by apocas** [delian/node-netflowv9#4]
I have a Cisco 7606, with Netflow v5 everything works well but with v9 I get this:

  NetFlowV9 Unknown template/option data with flowset id 256 +1ms
  NetFlowV9 Undecoded flows +0ms { header:
   { version: 9,
     count: 32,
     uptime: 2440412596,
     seconds: 1417567190,
     sequence: 130285,
     sourceId: 515 },
  flows: [] }
  NetFlowV9 compile template 257 +1ms
  NetFlowV9 Unknown NF type 51 +1ms

node_modules/node-netflowv9/netflowv9.js:185
                throw new Error('Unknown NF Type');

Any idea?

Thanks,

**Comment by lghamie** [comment]
Same problem here, i keep getting:
```
  NetFlowV9 Undecoded flows +0ms { header: 
   { version: 9,
     count: 67,
     uptime: 775141043,
     seconds: 1400237403,
     sequence: 2421693,
     sourceId: 1677787446 },
  flows: [] }
  NetFlowV9 compile template 256 +5ms
```
Untill i get: 
```
  NetFlowV9 Unknown NF type 234 +0ms
/netflowv9.js:185
                throw new Error('Unknown NF Type');
```

And that happens when I get the first template definition.

Thanks for the help!

**Comment by delian** [comment]
Could you please do "npm ll" for me?


Delian

**Comment by lghamie** [comment]
There we go:

```
myproj@1.0.0
│ mypath
│ 
├─┬ cassandra-driver@1.0.2
│ │ DataStax Node.js Driver for Apache Cassandra
│ │ https://github.com/datastax/nodejs-driver.git
│ │ https://github.com/datastax/nodejs-driver
│ ├── async@0.9.0
│ │   Higher-order functions and common patterns for asynchronous code
│ │   https://github.com/caolan/async.git
│ │   https://github.com/caolan/async
│ ├── long@2.2.3
│ │   A Long class for representing a 64-bit two's-complement integer value.
│ │   https://github.com/dcodeIO/Long.js.git
│ │   https://github.com/dcodeIO/Long.js
│ └── node-uuid@1.4.1
│     Rigorous implementation of RFC4122 (v1 and v4) UUIDs.
│     https://github.com/broofa/node-uuid.git
│     https://github.com/broofa/node-uuid
└─┬ node-netflowv9@0.2.1
  │ NetFlow Version 1,5,7,9 compatible library for Node.JS. It also support NetFlow v9 options template & data
  │ https://github.com/delian/node-netflowv9.git
  │ https://github.com/delian/node-netflowv9
  └─┬ debug@1.0.4
    │ small debugging utility
    │ git://github.com/visionmedia/debug.git
    └── ms@0.6.2
        Tiny ms conversion utility
        git://github.com/guille/ms.js.git
```

**Comment by delian** [comment]
Ahh, I know what that is.

NetFlow v9 defines NetFlow types bellow 200.
NetFlow types above that number belong to IPFIX (Netflow v10).
Type 234 is the type for the VRF table.
It is not a complex thing to add IPFIX and it is in my list. But I had some
troubles getting structured and strict specification and I have no where to
test it. But give me some time until Monday, I can try to add all of the
types I can easily find from IPFIX in this library for you. That should be
something easy.


Delian

**Comment by lghamie** [comment]
Well, that would be more than awesome.

But i think that the problem could be because im using CFLOW, or it doesnt
matter?

**Comment by delian** [comment]
No, it is basically the same.
All those follow the same specification, which at the end is defined as
IPFIX.
For all fields from 1 to 127, they keep the same as in netflow v9 to
preserve compatibility with Cisco.
Fields from 128+ are IPFIX fields and they are special. Some of them has
new types and new decoding, sometimes even is acceptable to be having
compression of the data field, which adds a certain level of complexity and
this is why it was kind of left to be the last thing to add here in this
small package.
But some fields may be very easy to implement, and I could do it very fast,
and if we are lucky it may be enough for the work with your flow source.


Delian

**Comment by lghamie** [comment]
That would be great, thanks!

**Comment by delian** [comment]
Actually, if you have a time, do npm update and try again (should be 0.2.4).
I've just added a lot of new IPFIX types to this little module. Your
missing type is there. However, there were several other, that have to wait
as they require a bit of a new code.
Please test and tell me what the result is


Delian

**Comment by lghamie** [comment]
Thanks! I'll try tomorrow!

**Comment by lghamie** [comment]
Thanks! it works like a charm!
