### ISSUE TITLE
in_bytes undefined

### ISSUE THREAD

**Issue by bjoernhoefer** [delian/node-netflowv9#6]
Dear all,

thank you for building such a great tool - it helps me do my job pretty better ;-)

We have several Cisco ASA Firewalls with the following firmware-levels:
ASA 5545 - Version 9.1(3)
ASA 5520 - Version 8.4(4)9
ASA 5520 - Version 9.1(4)

On all Firewalls I'm suffering with the same issue, I can not see how many bytes are transferred.

The code I'm using is pretty straightforward - so I don't think I made a mistake here - but to make sure...

```
var Collector = require('node-netflowv9');
Collector(function(flow) {
Object.keys(flow.flows).forEach(function(flow_nr){
if (flow.flows[flow_nr].ipv4_src_addr) console.log("Source: "+flow.flows[flow_nr].ipv4_src_addr + "\tDestination: "+flow.flows[flow_nr].ipv4_dst_addr + " \tProtocol: " + flow.flows[flow_nr].protocol + " \tsrc-port: " + flow.flows[flow_nr].l4_src_port + " \tdst-port: " + flow.flows[flow_nr].l4_dst_port + " \tbytes: " + flow.flows[flow_nr].in_bytes)
})
}).listen(25560);

```
An (anonymous/shortend) example of a flow. 
```
{ header:
   { version: 9,
     count: 17,
     uptime: 3106950079,
     seconds: 1424420284,
     sequence: 369182748,
     sourceId: 0 },
  flows:
   [ { flowId: 4031249624,
       ipv4_src_addr: '1.2.3.4',
       l4_src_port: 41934,
       input_snmp: 4,
       ipv4_dst_addr: '1.2.3.4',
       l4_dst_port: 53,
       output_snmp: 3,
       protocol: 17,
       icmpTypeIPv4: 0,
       icmpCodeIPv4: 0,
       postNATSourceIPv4Address: '1.2.3.4',
       postNATDestinationIPv4Address: '1.2.3.4',
       postNAPTSourceTransportPort: 41934,
       postNAPTDestinationTransportPort: 53,
       firewallEvent: 2,
       unknown_type_33002: '07e1',
       observationTimeMilliseconds: 1424420284201,
       initiatorOctets: 123,
       responderOctets: 320,
       flowStartMilliseconds: 1424420284161,
       fsId: 263 },
     { ipv4_src_addr: '1.2.3.4',
       l4_src_port: 57553,
       input_snmp: 27,
       ipv4_dst_addr: '1.2.3.4',
       l4_dst_port: 139,
       output_snmp: 4,
       protocol: 6,
       icmpTypeIPv4: 0,
       icmpCodeIPv4: 0,
       postNATSourceIPv4Address: '1.2.3.4',
       postNATDestinationIPv4Address: '1.2.3.4',
       postNAPTSourceTransportPort: 57553,
       postNAPTDestinationTransportPort: 139,
       firewallEvent: 3,
       unknown_type_33002: '03e9',
       observationTimeMilliseconds: 1424420284201,
       unknown_type_33000: '818dd109aea26e3700000000',
       unknown_type_33001: '000000000000000000000000',
       fsId: 260 },
```

With the mentioned code above my output looks like:
```
Source: 1.2.3.4    Destination: 1.2.3.4      Protocol: 17    src-port: 46083         dst-port: 53    bytes: undefined
```

Do you got an idea, how I can get to the bytes?

Thank you in advance.

Björn

**Comment by delian** [comment]
With the oldest versions of the library, if there were unknown type (for
which I have no specific decoding applied) the library was throwing an
error.
With the latest update, I decided to make it to add "unknown_type_XXXX"
where XXXX is the type id and the value in HEX (as I have no idea how to
decode it).
You can easily convert it to bytes with something like (new
Buffer(flow['unknown_type_33000'],'hex'))
In the next release, I plan to redesign a little the internal structure, so
I will allow the end user to add its own decoding functions for certain
types, as long as this user known what he/she is doing.

I also want to mention that types above 33000 are definitely not a
standard, so you have to look for a vendor documentation that describes
what they represent and how to decode them...


Delian

**Comment by bjoernhoefer** [comment]
Dear delian,

thank you for the fast answer - what I found out the types 33xxx  are not related to a byte size... 
They are related to ACL's and events - Cisco ASA's are fiewalls, so its legitimate that they provide such information (which no one needs ;-) ) found here: http://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/guide/asa_netflow.html

Any other ideas?

Before using this library I've used nfdump which could provide me this information, so I at least know, that the information is there :-)

**Comment by delian** [comment]
Let me check the documentation. However, according to IPFIX (the netflow
standard) such type should not exist. But let me see and I will get back on
you

**Comment by bjoernhoefer** [comment]
thank you very much - what I found in this docs (and understood) is that the size is somehow calculated from a delta...

**Comment by bjoernhoefer** [comment]
Dear delian,

did you find any time to take a look at the problem?

Thanks in advance

björn

**Comment by delian** [comment]
Sorry for the delay, I didn't had the time. I will try to check it tonight


Delian

**Comment by bjoernhoefer** [comment]
No problem, just wanted to remind you ;-)

**Comment by delian** [comment]
Hi,
I've build and uploaded a new version of the library.
Your properties are not there yet. I am not sure how to decode them and I have no where to test the decode. But you can do it.

The new version 0.2.5 supports user extension of the netflow type decoding (sorry for my english).
The idea is, that you can define your own decoding code for any types. You can overwrite the old decoding, or you can write your own decoding for new types. How that works is written in the README.md file. Please read it.

So lets try to decode your properties (following the Cisco documentation you send me).

Try a code like this and tell me what is the result:

    var colObj = Collector(function (flow) { console.log(flow) });
    colObj.listen(5000);
    
    var aclDecodeRule = {
      12: 'o["$name"] = { aclId: buf.readUInt32BE($pos), aclLineId: buf.readUInt32BE($pos+4), aclCnfId: buf.readUInt32BE($pos+8)};'
    };
    
    colObj.nfTypes[33000] = { name: 'nf_f_ingress_acl_id', compileRule: aclDecodeRule };
    colObj.nfTypes[33001] = { name: 'nf_f_egress_acl_id', compileRule: aclDecodeRule };
    colObj.nfTypes[33002] = { name: 'nf_f_fw_ext_event', compileRule: {
      2: 'o['$name']=buf.readUInt16BE($pos);'
    } };
    colObj.nfTypes[40000] = { name: 'nf_f_username', compileRule: {
      0: 'o["$name"] = buf.toString("utf8",$pos,$pos+$len);'
    } };

Unless I have a typo somewhere, or forgot a property, this should allow you to decode the properties you are missing.

**Comment by bjoernhoefer** [comment]
Dear delian,

I recently found the "error"...

It seems that our ASA Firewall doesn't send bytes_in or bytes_out - instead it send initiatorOctets  and responderOctets.

So I'm using them as an alternative.

Issue can be close - thanks so far.


Björn
